This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./MA-Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file MA-Thesis.acn....done (29 entries accepted, 0 rejected).
Sorting entries....done (146 comparisons).
Generating output file MA-Thesis.acr....done (36 lines written, 0 warnings).
Output written in MA-Thesis.acr.
Transcript written in MA-Thesis.alg.
